### ISSUE TITLE
Next.js support

### ISSUE THREAD

**Issue by arnaudmanaranche** [xolvio/storybook-webpack-federation-plugin#13]
First of all thanks for this plugin !

Does this package is supporting with a Next.js project ?
What to include inside the `import("./bootstrap");` file ?

**Comment by ScriptedAlchemy** [comment]
I’m actively working with the next.js team and rebuilt most of next to be webpack 5 ready - they have already started merging incrementally. The collaboration with Dan Abramov, Next, and Weback delayed it a bit - but we now have fast refresh working (needed to modify the graph so modules are self aware)

**Comment by arnaudmanaranche** [comment]
Lots of new docs/contents about using Module Federation with Next.js have been published:

- https://github.com/module-federation/nextjs-mf
- https://gist.github.com/jherr/dd10bc34448590a2661a0c6acbcc7e8a
- https://github.com/module-federation/module-federation-examples

Maybe now it's possible to use this plugin with a Next.js project ?

Thanks @ScriptedAlchemy !

**Comment by ScriptedAlchemy** [comment]
It's a big hack. But it works. It could be improved to like a hashed external file instead of inlineing react into the document. But simple enough PR
