### ISSUE TITLE
Upgrade to b17 support.

### ISSUE THREAD

**Issue by jherr** [xolvio/storybook-webpack-federation-plugin#21]
The `exposes` syntax has changed from:

```
{
   ...
  exposes: {
    Header: './src/Header' 
  }
}
```

to 

```
{
   ...
  exposes: {
    './Header': './src/Header' 
  }
}
```

So there needs to be a slight modification to:

https://github.com/xolvio/storybook-webpack-federation-plugin/blob/master/src/index.js#L23

I think. I haven't tested it.

It's probably just:

```
                .replace(removePrefix, "./")
```

**Comment by jeremiahdir** [comment]
Issue created by container consumption breaking by b17 changes laid out by issue on demo project here: https://github.com/xolvio/webpack-federation-storybook-design-systems-demo/issues/8
(apologies if I am messy in my contribution patterns, I am new to contributing to open source projects. Please feel free to let me know if I can change things to be cleaner)
